[project]
name = "searchlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Josh Lo", email = "Josh.Lo@skyworksinc.com" }
]
requires-python = "==3.12"
dependencies = []

[project.scripts]
searchlib = "searchlib:main"

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"
